version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
only_commits:
  files:
    - Serilog.Settings.Delegates.sln
    - src/Serilog.Settings.Delegates/
deploy:
- provider: NuGet
  api_key:
    secure: UDW8eHW8VDRzr9YolMr6Cs2h6BaieEJvQASj/2xU1x+hG0LLZ8I6d2k0pQRl3oVi
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: +EUQOpgfGayDA+QMrOqaI9wi2mUYdI3RrTU2hJNTMAIfBm/HAIQkCPxIGx+8nDeA
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
